events {}

http {
	include /etc/nginx/mime.types;
	
	server {
		listen 443 ssl;
		server_name vgalmich.42.fr;

		# Use mounted secrets (preferred) or files from /etc/nginx/ssl if you mount them
		ssl_certificate /run/secrets/fullchain.pem;
		ssl_certificate_key /run/secrets/privkey.pem;
		ssl_protocols TLSv1.2 TLSv1.3;

		root /var/www/html;
		index index.php index.html index.htm;

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_split_path_info ^(.+\.php)(/.+)$;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_param PATH_INFO $fastcgi_path_info;
			fastcgi_index index.php;
			fastcgi_pass wordpress:9000;
		}

		# Deny access to hidden files and secrets
		location ~ /run/secrets/ {
			deny all;
			return 404;
		}
	}
}
