# the services part
services:
#mariadb
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    secrets:
      - db_root_password
      - db_password
    networks :
      - inception
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost --silent || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
#nginx
  nginx:
    image: nginx:user
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
#wordpress
  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    networks:
      - inception
    restart: always

# the volumes part
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/vgalmich/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/vgalmich/data/wordpress
      o : bind
      type : none

# the networks part
networks:
  inception:
    name: inception

# the secrets part
secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt